MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - 10.14                  # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - 10.14                  # [osx and x86_64]
c_compiler_version:        # [linux]
  - '10.3.0'                 # [linux]
cxx_compiler_version:      # [linux]
  - '10.3.0'                 # [linux]
cdt_name:
  - cos7
root_base:
  - 6.26.6
