channel_sources:
- conda-forge, default
channel_targets:
- conda-forge main
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - 10.14                  # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - 10.14                  # [osx and x86_64]
gsl:
- '2.7'
