{% set name = "OstapHEP" %}
{% set version = "1.4.9.1" %}
{% set hash = "8cc2778a6172c2a024e8d523e0f9f17e8a08d54fd0d5e9baecb5f27778c3b7fd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OstapHEP/ostap/archive/v{{ version }}.tar.gz
  sha256: {{ hash }}
  folder: ostap

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - root_base
    - root-binaries
    - root-dependencies
    - python
    - gsl
  run:
    - python
    - future
    - ipython
    - configparser  # [py2k]
    - scipy
    - numpy
    - pathos
    - dill
    - multiprocess
    - ppft
    - libdb
    - bsddb3
    - terminaltables
test:
  imports:
    - ostap
    - ostap.core.core

about:
  home: https://github.com/OstapHEP/ostap
  license: BSD-3-Clause
  license_family: BSD
  license_file: ostap/LICENSE
  dev_url: https://github.com/OstapHEP/ostap
  summary: |
    The Ostap project is a community-driven
    initiative aiming to provide more user friendly and more intuitive interface
    to ROOT and PyROOT and extending the existing functionality.
  description: |
    Nowadays ROOT and PyROOT are de-facto standard tools for performing physics analysis.
    The Ostap project is a community-driven initiative aiming to provide more user friendly
    and more intuitive interface to ROOT and PyROOT and extending the existing functionality.
    Project started in 2009 from the private collections of python functions
    used in Kali - framework for calibration of LHCb electromagnetic calorimeter.
    A lot of functionality is picked from Bender project - python based physics analysis environment used in LHCb experiemnt.
    Till Autumn 2016 the project was a part of LHCb software suit and with great success has been used
    for preparation of approximately 30 physics papers. A standalone, LHCb independent version, has appeared at start of 2017
    Key features include:
     * Very easy manipulations with ROOT and RooFit objects: histograms, trees, datasets, etc
     * Very easy interface to RooFit machinery
     * Extended set of models.PDFs for RooFit
     * Powerful, pickle-based persistency for object
     * Interactive ostap analysis environment

extra:
  recipe-maintainers:
    - TatianaOvsiannikova
    - VanyaBelyaev
