{% set name = "OstapHEP" %}
{% set version = "1.7.1.8" %}
{% set root_version = "6.24.6" %}
package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/OstapHEP/ostap/archive/v{{ version }}.tar.gz
  sha256: e32e78702dbb080704f1162ffbf2703ffc3d9e266680530074af1e3b39945e1e
  folder: ostap
  patches:
    - 0001-fix-executables-path.patch

build:
  number: 0
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - root_base <{{ root_version }}
    - python
    - gsl
    - scipy
    - more-itertools
    - psutil
    - bsddb3
    - terminaltables
  run:
    - python
    - future
    - ipython
    - scipy
    - numpy
    - pathos
    - dill
    - multiprocess
    - more-itertools
    - ppft
    - psutil
    - libdb
    - bsddb3
    - terminaltables
test:
  imports:
    - ostap
    - ostap.core.core

about:
  home: https://github.com/OstapHEP/ostap
  license: BSD-3-Clause
  license_file: ostap/LICENSE
  dev_url: https://github.com/OstapHEP/ostap
  summary: |
    The Ostap project is a community-driven
    initiative aiming to provide more user friendly and more intuitive interface
    to ROOT and PyROOT and extending the existing functionality.
  description: |
    Nowadays ROOT and PyROOT are de-facto standard tools for performing physics analysis.
    The Ostap project is a community-driven initiative aiming to provide more user friendly
    and more intuitive interface to ROOT and PyROOT and extending the existing functionality.
    Project started in 2009 from the private collections of python functions
    used in Kali - framework for calibration of LHCb electromagnetic calorimeter.
    A lot of functionality is picked from Bender project - python based physics analysis environment used in LHCb experiment.
    Till Autumn 2016 the project was a part of LHCb software suit and with great success has been used
    for preparation of approximately 30 physics papers. A standalone, LHCb independent version, has appeared at start of 2017
    Key features include:
     * Very easy manipulations with ROOT and RooFit objects: histograms, trees, datasets, etc
     * Very easy interface to RooFit machinery
     * Extended set of models.PDFs for RooFit
     * Powerful, pickle-based persistency for object
     * Interactive ostap analysis environment

extra:
  recipe-maintainers:
    - TatianaOvsiannikova
    - VanyaBelyaev
