schema_version: 1

context:
  name: OstapHEP
  version: "3.7.4.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/OstapHEP/ostap/archive/v${{ version }}.tar.gz
  sha256: d5601cd9e373d48b0366f31a1ddcd68ee1470a2651fd9e288be4261e3b1274dd
  target_directory: ostap
  patches:
    - 0001-fix-executables-path.patch

build:
  number: 6
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - ninja
    - pip
    - setuptools 
    - wheel 
  host:
    - root_base
    - root_cxx_standard
    - python
    - gsl
    - scipy
    - numpy
    - numba
    - cffi
    - pip
    - pathos
    - dill
    - multiprocess
    - ppft
    - joblib
    - ipyparallel
    - zstandard
    - more-itertools
    - sortedcontainers
    - psutil
    - tabulate
    - terminaltables
    - pathvalidate
    - packaging 
    - libdb
    - duckdb
    - fasteners
    - statsmodels
    - pandas
    - xgboost
    - catboost
    - lightgbm
    - sweetviz
    - hep_ml
    - py-cpuinfo 
  run:
    - python
    - ipython
    - root_base
    - gsl
    - scipy
    - numpy
    - numba
    - cffi
    - pathos
    - dill
    - multiprocess
    - ppft
    - joblib
    - ipyparallel
    - zstandard
    - more-itertools
    - sortedcontainers
    - psutil
    - tabulate
    - terminaltables
    - pathvalidate
    - packaging
    - libdb
    - duckdb
    - fasteners
    - statsmodels
    - pandas
    - xgboost
    - catboost
    - lightgbm
    - sweetviz
    - hep_ml
    - py-cpuinfo 
    - parallel 
    
tests:
  - python:
      imports:
        - ostap
        - ostap.core.core
        - ostap.core.pyrouts

about:
  license: BSD-3-Clause
  license_file: ostap/LICENSE
  summary: >
    The Ostap project is a community-driven initiative aiming to provide more
    user friendly and more intuitive interface to ROOT and PyROOT and extending
    the existing functionality.
  homepage: https://github.com/OstapHEP/ostap
  repository: https://github.com/OstapHEP/ostap

extra:
  recipe-maintainers:
    - TatianaOvsiannikova
    - VanyaBelyaev
