schema_version: 1

context:
  name: OstapHEP
  version: 3.6.6.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/OstapHEP/ostap/archive/v${{ version }}.tar.gz
  sha256: dfc071fe9dcee918c00948a5b5b4c0fefac5a5ef461a466566b2c52980636827
  target_directory: ostap
  patches:
    - 0001-fix-executables-path.patch
    - 0002-fix-portability-for-non-glibc.patch

build:
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - ninja
    - pip
    - python
  host:
    - root_base
    - root_cxx_standard
    - python
    - gsl
    - scipy
    - numpy
    - pip
  run:
    - python
    - ipython
    - root_base
    - gsl
    - scipy
    - numpy
    - cffi
    - pathos
    - dill
    - multiprocess
    - ppft
    - joblib
    - ipyparallel
    - zstandard
    - more-itertools
    - sortedcontainers
    - psutil
    - tabulate
    - terminaltables
    - libdb
    - parallel

tests:
  - python:
      imports:
        - ostap
        - ostap.core.core
        - ostap.core.pyrouts

about:
  license: BSD-3-Clause
  license_file: ostap/LICENSE
  summary: >
    The Ostap project is a community-driven initiative aiming to provide more
    user friendly and more intuitive interface to ROOT and PyROOT and extending
    the existing functionality.
  homepage: https://github.com/OstapHEP/ostap
  repository: https://github.com/OstapHEP/ostap

extra:
  recipe-maintainers:
    - TatianaOvsiannikova
    - VanyaBelyaev
