schema_version: 1

context:
  name: OstapHEP
  version: "3.6.9.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/OstapHEP/ostap/archive/${{ version }}.tar.gz
  sha256: 2e8b2bbb3d209378e63484b7a37742834488958c8a538d88c2544f11c94ffe1b
  target_directory: ostap
  patches:
    - 0001-fix-executables-path.patch

build:
  number: 0
  skip:
    - win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - ninja
    - pip
    - python
  host:
    - root_base
    - root_cxx_standard
    - python
    - gsl
    - scipy
    - numpy
    - pip
  run:
    - python
    - ipython
    - root_base
    - gsl
    - scipy
    - numpy
    - cffi
    - pathos
    - dill
    - multiprocess
    - ppft
    - joblib
    - ipyparallel
    - zstandard
    - more-itertools
    - sortedcontainers
    - psutil
    - tabulate
    - terminaltables
    - libdb
    - parallel

tests:
  - python:
      imports:
        - ostap
        - ostap.core.core
        - ostap.core.pyrouts

about:
  license: BSD-3-Clause
  license_file: ostap/LICENSE
  summary: >
    The Ostap project is a community-driven initiative aiming to provide more
    user friendly and more intuitive interface to ROOT and PyROOT and extending
    the existing functionality.
  homepage: https://github.com/OstapHEP/ostap
  repository: https://github.com/OstapHEP/ostap

extra:
  recipe-maintainers:
    - TatianaOvsiannikova
    - VanyaBelyaev
