travis:
  secure:
    BINSTAR_TOKEN: Hg3XHrQT8Mv00hz170X4BCezPYlNZVp/vrAxtkVlk++F8wAYxtcZQinEOMNXIDdUi4CdPLhypTwVv1ThnDl83YYPtQa5F9bU8BPBNAk6R5IhH24eo6+FMZImJrFeCV8Y/VR3A+NKSb5CAJHCb+nKo0cBd+7TB3vrfJsDBsUJIBR0eRWPnK9ZwtJ5X+SVUvZLnF4DRU9gRaRJThtxPthJ//P8CEUe1F+IAvjnnlZM6xuHPNfUaSDDI9SLkJhvmoAoFM0VlWiSAaaPTRExCrgm4akNiintPMzYIf9l0yoJveEo2exSEmMzYcYQUMdMExNXEtEWwoJInX92+n91gF52MfFSebP2Mahcm9YgILzuUPMLvitTQ5+BYKofvi7zH1NDNJEuQyZ9AMylNtr6PMBaOYWhfg6Lo99f/wLnSpmg450B1OaO1Xon/9fmaef6utLAJR24LweiQWwsfyk93dEGV20TW7sASTd66e+fFx1nHnd0TvcuWGql7ZY4KZ14YfQi3cOzlB2PCc/OI8wqV+lggMw7WPU813CnaTjwJpSb4OJGJRqRvXqIuaG39FP2/mgyN2w7QC+vo7H84aUAQY8cfaDBKR6rfX8k+qTV+iIG48/Wm3ZetPfIVvVCvDiz/H5o7IMhpcEWFiR9erY2BrI/Nwg2iddGXpTJYP3WcDCoCcc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
